### ISSUE TITLE
I tried to use other filters but the results are strange.

### ISSUE THREAD

**Issue by 1094442522** [fpiernas/FBP#2]
Hi, @fpiernas 
I tried to use other filters ,for example, the Hamming window, but the results are strange.
Have you tried other methods besides sinusoidal filtering?

**Comment by fpiernas** [comment]
Hi, I didn't test other filters because the sinusoidal was giving me good results already. Hamming filter is more complex than sinusoidal, so adjusting it can be tricky.

I did see that if you don't multiply by 0 the first and last harmonic in the Fourier transform, the result is blurry and noisy.

**Comment by 1094442522** [comment]
Thank you for your experience~
